NAME_2_LATEX = {
    "RandomSeed": r"$\large{\text{seed}}$",
    "Tau": r"$\large{\tau}$",
    "TauDev": r"$\large{\tau^{\sigma}}$",
    "TauDist": r"$\large{\tau^{\text{dist}}}$",
    "Accel": r"$\large{a}$",
    "AccelDev": r"$\large{a^{\sigma}}$",
    "AccelDist": r"$\large{a^{\text{dist}}}$",
    "Decel": r"$\large{b}$",
    "DecelDev": r"$\large{b^{\sigma}}$",
    "DecelDist": r"$\large{b^{\text{dist}}}$",
    "minGap": r"$\large{s_0}$",
    "minGapDev": r"$\large{s_0^{\sigma}}$",
    "minGapDist": r"$\large{s_0^{\text{dist}}}$",
    "speedFactor": r"$\large{\text{SF}_v}$",
    "speedDev": r"$\large{\text{SF}^{\sigma}}$",
    "speedFactorDist": r"$\large{\text{SF}^{\text{dist}}}$",
    "impatience": r"$\large{\text{impatience}}$",
    "impatienceDev": r"$\large{\text{impatience}^{\sigma}}$",
    "lcStrategic": r"$\large{\text{lcStrategic}}$",
    "lcStrategicDev": r"$\large{\text{lcStrategic}^{\sigma}}$",
    "lcAssertive": r"$\large{\text{lcAssertive}}$",
    "lcAssertiveDev": r"$\large{\text{lcAssertive}^{\sigma}}$",
    "FleetComposition": r"$\large{p_{\text{truck}}}$",
    'TruckSpeedFactor': r'$\large{\text{SF}_{\text{truck}}}$',
    'TruckAccel': r"$\large{a_{\text{truck}}}$",
    'TruckTau': r'$\large{\tau_{\text{truck}}}$',
    'TruckDecel': r"$\large{b_{\text{truck}}}$"
}



ORDERED_VARIABLES = {
    "speedFactor": 0,
    "Accel": 1,
    "Decel": 2,
    "Tau": 3,
    "minGap": 4,
    "RandomSeed": 5,
    "speedDev": 6,
    "DecelDist": 7,
    "DecelDev": 8,
    "impatience": 9,
    "minGapDist": 10,
    "TauDist": 11,
    "speedFactorDist": 12,
    "TauDev": 13,
    "minGapDev": 14,
    "AccelDist": 15,
    "AccelDev": 16,
    "impatienceDev": 17,
    "lcAssertive": 18,
    "lcAssertiveDev": 19,
    "lcStrategic": 20,
    "lcStrategicDev": 21,
}

ORDERED_VARIABLES_TRUCK = {
    "FleetComposition": 0,
    "Accel": 1,
    "speedFactor": 2,
    "Decel": 3,
    "Tau": 4,
    "RandomSeed": 5,
    "speedDev": 6,
    "DecelDist": 7,
    "minGap": 8,
    "DecelDev": 9,
    "AccelDev": 10,
    "impatience": 11,
    "AccelDist": 12,
    "minGapDist": 13,
    "TauDev": 14,
    "TauDist": 15,
    "minGapDev": 16,
    "TruckAccel": 17,
    "speedFactorDist": 18,
    "TruckDecel": 19,
    "TruckTau": 20,
    "TruckSpeedFactor": 21,
}
