Metadata:
  # The name will also show up as the main folder for simulation
  name: SumoDefaults
  author: mcschrader@crimson.ua.edu
  output: ${oc.env:PROJECT_ROOT}/tmp/${Metadata.name}/${datetime.now:%m.%d.%Y_%H.%M.%S}
  cwd: ${.output}/${.run_id} # this is not a place to save simulation files, bc SUMO can't acccept commas in file paths
  run_id: ???
  simulation_root: ${oc.env:PROJECT_ROOT}/simulation
  random_seed: 42
Blocks:
  # this is just a dummy block so I don't have to change the random seed paths
  # in later simulations
  SobolSequenceConfig:
    N: 1
    calc_second_order: False
    save_path: dummy
    params:
      RandomSeed:
        bounds: [0, 100_000]
        # all subsequent blocks will use this seed, which is actually set in the iterator
        val: ${Blocks.SeedConfig.seed}

  SeedConfig:
    num_samples: 100
    range:
      - 0
      - 100_000
    seed: ???

Pipeline:
  pipeline:
    - block: RunSimulation
      parallel: True
      number_of_workers: 64
      producers:
        - function: ${import:producers.generate_random_seed}
          config: ${Blocks.SeedConfig}
      consumers:
        - function: ${import:xml.update_output_file}
          config: ${Blocks.XMLChangeOutputConfig}
        - function: vehicle_distributions.create_simple_sampled_distribution
          config: ${Blocks.SampledSimpleCFConfig}
        - function: routesampler.call_random_trips
          config: ${Blocks.RandomTripsConfig}
        - function: routesampler.call_route_sampler
          config: ${Blocks.RouteSamplerConfig}
        - function: simulation.run_sumo
          config: ${Blocks.SimulationConfig}
        - function: ${import:xml.convert_xml_to_parquet}
          config: ${Blocks.XMLConvertConfig}
        - function: ${import:xml.convert_xml_to_parquet}
          config:
            source: ${Blocks.XMLChangeOutputConfig.changes[1].new_output}
            target: ${Metadata.cwd}/detectors.parquet
            delete_source: true
            elements:
              - name: interval
                attributes:
                  - begin
                  - end
                  - id
                  - sampledSeconds
                  - nVehEntered
                  - nVehLeft
                  - nVehSeen
                  - meanSpeed
                  - meanTimeLoss

        - function: external.src.sa_helpers.metrics.get_sa_results
          config:
            trip_info_file: ${Blocks.XMLConvertConfig.target}
            detector_file: ${Metadata.cwd}/detectors.parquet
            warmup_time: ${Blocks.SimulationConfig.warmup_time}
            total_fuel_l: ???
            average_fc: ???
            average_speed: ???
            average_delay: ???
            average_travel_time: ???
            delay_ratio: ???
        - function: emissions.fast_total_energy
          config: ${Blocks.FuelTotalConfig}
        - function: ${import:io.save_config}
          config:
            save_path: ${Metadata.cwd}/config.yaml
        - function: ${import:io.rm_file}
          config:
            rm_files:
              - ${Blocks.XMLChangeOutputConfig.changes[0].target}
              - ${Blocks.XMLChangeOutputConfig.changes[1].target}
              - ${Metadata.cwd}/detectors.parquet
              - ${Metadata.cwd}/random.trips.xml
              - ${Metadata.cwd}/vehDist.in.xml
              - ${Metadata.cwd}/routes.add.xml
              - ${Metadata.cwd}/routesampler.rou.xml
              - ${Metadata.cwd}/per_phase.e2.add.xml
